---
- name: Distro specific installation
  include: "{{ ansible_distribution }}.yml"
  tags: install

- name: Copy ufw defaults
  template:
    src: default/ufw
    dest: /etc/default/ufw
  notify: Restart ufw

- name: Copy ufw configurations
  template:
    src: "ufw/{{ item }}"
    dest: "/etc/ufw/{{ item }}"
  notify: Restart ufw
  with_items:
    - sysctl.conf
    - before.rules

- name: Firewall configuration should be private
  file:
    path: '{{ item }}'
    mode: 'o-rwx,g-xw'
    recurse: yes
  with_items:
    - /etc/ufw
    - /var/lib/ufw

# Reset to delete old, removed rules
- name: Reset ufw
  ufw:
    state: reset

- name: Add SSH rule(s), so we don't lose connection
  ufw:
    rule: allow
    port: "{{ ufw_ssh_port }}"

- name: Enable ufw
  ufw:
    state: enabled

- name: Enable and start ufw service
  service:
    name: ufw
    state: started
    enabled: yes

