---
- name: Check if certificate already exists
  stat:
    path: "/etc/letsencrypt/live/{{ letsencrypt_domain }}"
  register: domain_folder

- set_fact:
    letsencrypt_new_domains: "{{ letsencrypt_new_domains + [letsencrypt_domain] }}"
  when: not domain_folder.stat.exists
  changed_when: not domain_folder.stat.exists
  notify: Request letsencrypt certificate

