

- name: Add groups admin, sudo, wheel
  group:
    name: '{{ item }}'
  with_items:
    - 'admin'
    - 'sudo'
    - 'wheel'

- name: Add the user 'rien'
  user:
    name: rien
    comment: Rien Maertens
    groups: systemd-journal,users,lp,sudo,admin,wheel
    createhome: no
    home: '/home/rien'
    shell: /bin/zsh

- name: Create user dir
  file:
    path: '/home/rien'
    state: directory
    owner: rien
    group: rien

- set_fact:
    dotfiles_repo: 'https://github.com/R13N/puntbestanden.git'
    dotfiles_user: 'rien'
    dotfiles_user_home: '/home/rien'

# Install dotfiles
- include: dotfiles.yml

- name: Install rbenv
  git:
    repo: https://github.com/rbenv/rbenv.git
    dest: '/home/rien/.rbenv'

- name: Install ruby-build
  git:
    repo: https://github.com/rbenv/ruby-build.git
    dest: '/home/rien/.rbenv/plugins/ruby-build'

- name: User owns rbenv directory
  file:
    path: '/home/rien/.rbenv'
    owner: rien
    group: rien
    recurse: yes
