---
- name: CentOS droplet hosted by Digital Ocean.
  hosts: beata

  roles:
    - common

    - role: authorized_keys
      with_vars:
        authorized_keys_users:
          - name: root
            home: /root
          - name: screenshot
            home: /srv/http/screenshots
      tags:
        - authorized_keys

    - role: ebooks
      tags:
        - ebooks
        - sites

    - role: screenshots
      tags:
        - screenshots
        - sites

    - role: transmission
      tags:
        - transmission

    - role: test_letsencrypt
      tags:
        - test

    - role: theatervolta
      tags:
        - theatervolta
        - sites
