---
- name: CentOS droplet hosted by DigitalOcean.
  hosts: gunnar

  roles:
    - role: common
      tags:
        - common
        - install


    - role: authorized_keys
      authorized_keys: "{{ rien_pubkey }}"
      authorized_keys_users:
        - name: root
          home: /root
      tags:
        - authorized_keys

    - role: user
      user_name: rien
      user_comment: Rien Maertens
      user_groups: systemd-journal,lp,sudo,admin,wheel
      user_home: '/home/rien'
      user_authorized_keys: "{{ rien_pubkey }}"
      user_shell: /bin/zsh
      user_dotfiles: false
      user_dotfiles_repo: 'git@github.com:R13N/puntbestanden.git'
      tags:
        - user

    - role: ebooks
      tags:
        - ebooks
        - sites

    - role: screenshots
      tags:
        - screenshots
        - sites

    - role: transmission
      tags:
        - transmission
      transmission_download_dir: /srv/transmission/downloaded
      transmission_incomplete_dir: /srv/transmission/incomplete
      # secret vars: see host_vars/gunnar.yml

    - role: test_letsencrypt
      tags:
        - test

    - role: theatervolta
      theatervolta_webroot: /srv/http/volta
      theatervolta_site: theatervolta.be
      tags:
        - theatervolta
        - sites

    - role: mail
      mail_hostname: gunnar.rxn.be
      mail_domain: rxn.be
      mail_main_user: rien
      mail_root_email: maertensrien@gmail.com
      tags:
        - mail
        - postfix
        - dovecot

    - role: seafile
      seafile_url: seafile.rxn.be
      seafile_admin_email: "{{ rien_email }}"
      tags:
        - seafile

  vars_files:
    - vars/secrets.yml
