---
- name: This is a droplet hosted by Digital Ocean.
  hosts: droplet

  roles:
    #- common
    #- ebooks
    #- latexbuilder
    #- test_aura
    #- transmission
    #- theatervolta
    #- marnixmount
    - user_rien
    #- screenshots
    #- authorized_keys
