---
- name: CentOS droplet hosted by DigitalOcean.
  hosts: gunnar

  roles:
    - role: common
      tags:
        - common
        - install


    - role: authorized_keys
      authorized_keys: "{{ rien_pubkey }}"
      authorized_keys_users:
        - name: root
          home: /root
      tags:
        - authorized_keys

    - role: ebooks
      tags:
        - ebooks
        - sites

    - role: screenshots
      tags:
        - screenshots
        - sites

    - role: transmission
      tags:
        - transmission
      transmission_download_dir: /srv/transmission/downloaded
      transmission_incomplete_dir: /srv/transmission/incomplete
      # secret vars: see host_vars/gunnar.yml

    - role: test_letsencrypt
      tags:
        - test

    - role: theatervolta
      theatervolta_webroot: /srv/http/volta
      theatervolta_site: theatervolta.be
      tags:
        - theatervolta
        - sites

    - role: mail
      mail_hostname: gunnar.rxn.be
      mail_domain: rxn.be
      mail_main_user: rien
      mail_root_email: maertensrien@gmail.com
      tags:
        - mail
        - postfix
        - dovecot

  vars_files:
    - vars/secrets.yml
