---
- name: Masjiene is a server with tons of storage
  hosts: masjiene
  roles:

    - common

    - role: authorized_keys
      authorized_keys: "{{ rien_pubkey }}\n{{ bert_pubkey }}"
      authorized_keys_users:
        - name: root
          home: /root
      tags:
        - authorized_keys
    - role: duckdns
      duckdns_domain: masjiene
      # token: see secrets.yml
      tags:
        - duckdns

    - role: user
      user_name: bert
      user_groups: sudo,wheel
      user_authorized_keys: "{{ bert_pubkey }}"
      tags:
        - user

    - role: user
      user_name: rien
      user_groups: sudo,wheel
      user_authorized_keys: "{{ rien_pubkey }}"
      tags:
        - user

    - role: transmission
      transmission_url: transmission.masjiene.rxn.be
      transmission_download_dir: /srv/transmission/downloaded
      transmission_incomplete_dir: /srv/transmission/incomplete
      # secret vars: see host_vars/masjiene.yml
      tags:
        - transmission

  vars_files:
    - vars/secrets.yml
