---
- name: Masjiene is a server with tons of storage
  hosts: masjiene
  roles:

    - common

    - role: authorized_keys
      authorized_keys: "{{ rien_pubkey }}\n{{ bert_pubkey }}"
      authorized_keys_users:
        - name: root
          home: /root
      tags:
        - authorized_keys
    - role: duckdns
      duckdns_domain: masjiene
      # token: see secrets.yml
      tags:
        - duckdns

    - role: user
      user_name: bert
      user_groups: sudo,wheel
      user_authorized_keys: "{{ bert_pubkey }}"
      tags:
        - user

    - role: user
      user_name: rien
      user_groups: sudo,wheel
      user_authorized_keys: "{{ rien_pubkey }}"
      tags:
        - user

    - role: transmission
      transmission_url: transmission.masjiene.rxn.be
      transmission_download_dir: /srv/transmission/downloaded
      transmission_incomplete_dir: /srv/transmission/incomplete
      # secret vars: see host_vars/masjiene.yml
      tags:
        - transmission

    - role: seafile
      seafile_url: "masjiene.rxn.be"
      seafile_admin_email: "{{ rien_email }}"
      tags: seafile

    - role: postfix
      postfix_main_user: rien
      postfix_aliases:
        - alias: rien
          to: "{{ rien_email }}"
        - alias: bert
          to: "{{ bert_email }}"
        - alias: seafile
          to: root
      postfix_hostname: masjiene.rxn.be
      postfix_domain: masjiene.rxn.be
      tags: postfix

    - role: ufw_rule
      ufw_ssh_port: 2222
      ufw_applications:
        - name: WWW Full
          rule: allow
      tags: ufw




  vars_files:
    - vars/secrets.yml
