---

- name: Ensure user's groups exist
  group:
    name: '{{ item }}'
  with_items: "{{ user_groups.split(',') }}"

- name: Add the user "{{ user_name }}"
  user:
    name: "{{ user_name }}"
    comment: "{{ user_comment }}"
    groups: "{{ user_groups }}"
    createhome: yes
    home: "{{ user_home }}"
    shell: "{{ user_shell }}"

- name: Fix permissions and ssh directory
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "u=rwx,g=rx,o="
  with_items:
    - "{{ user_home }}"
    - "{{ user_home }}/.ssh"

- name: Copy authorized_keys file
  copy:
    content: '{{ user_authorized_keys }}'
    dest: '{{ user_home }}/.ssh/authorized_keys'
    mode: u=rw,g=r,o=r
    owner: '{{ user_name }}'
    group: '{{ user_name }}'

# Install dotfiles
- include: dotfiles.yml
  when: user_dotfiles

#- name: Install rbenv
#  git:
#    repo: https://github.com/rbenv/rbenv.git
#    dest: '/home/rien/.rbenv'

#- name: Install ruby-build
#  git:
#    repo: https://github.com/rbenv/ruby-build.git
#    dest: '/home/rien/.rbenv/plugins/ruby-build'

#- name: User owns rbenv directory
#  file:
#    path: '/home/rien/.rbenv'
#    owner: rien
#    group: rien
#    recurse: yes
