---

- name: Ensure user's groups exist
  group:
    name: '{{ item }}'
  with_items: "{{ user_groups.split(',') }}"

- name: Add the user "{{ user_name }}"
  user:
    name: "{{ user_name }}"
    comment: "{{ user_comment }}"
    groups: "{{ user_groups }}"
    createhome: yes
    home: "{{ user_home }}"
    shell: "{{ user_shell }}"

- name: Fix permissions and ssh directory
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "u=rwx,g=,o="
  with_items:
    - "{{ user_home }}"
    - "{{ user_home }}/.ssh"

- name: Copy authorized_keys file
  copy:
    content: '{{ user_authorized_keys }}'
    dest: '{{ user_home }}/.ssh/authorized_keys'
    mode: u=rw,g=r,o=r
    owner: '{{ user_name }}'
    group: '{{ user_name }}'

# Install dotfiles
- name: Download and run dotfiles setup script
  command: "/bin/bash <(/bin/curl -sS {{ user_dotfiles_setup_script_url }})"
  when: user_dotfiles_setup_script_url is defined

