---
- name: Ensure there is a http user
  user:
    name: http
    shell: /usr/bin/nologin
    system: yes

- name: Install nginx on Arch
  pacman:
    name: nginx-mainline
    state: latest
  when: ansible_distribution == "Archlinux"

- name: Install nginx on CentOS
  yum:
    name: nginx
    state: latest
  when: ansible_distribution == "CentOS"

- name: Create vhost directories
  file:
    dest: "/etc/nginx/{{ item }}"
    state: directory
  with_items:
    - sites-enabled
    - sites-available

- name: Copy nginx config
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: "Restart webserver"

- name: Ensure nginx is enabled
  service:
    name: nginx
    enabled: yes
