---
- name: Ensure there is a http user
  user:
    name: http
    shell: /usr/bin/nologin
    system: yes

- name: Distribution specific installation
  include: "{{ ansible_distribution }}.yml"
  tags:
    - install

- name: Create vhost directories
  file:
    dest: "/etc/nginx/{{ item }}"
    state: directory
  with_items:
    - sites-enabled
    - sites-available

- name: Copy config
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: Restart nginx

- name: Copy snippets
  copy:
    src: "snippets/"
    dest: "/etc/nginx/snippets/"
  notify: Restart nginx

- name: Check configuration
  command: /usr/sbin/nginx -t

- name: Ensure nginx is enabled & running
  service:
    name: nginx
    state: started
    enabled: yes
