---
- name: Install nginx
  pacman: name=nginx-mainline state=latest

- name: Create vhost directoris
  file:
    dest: "/etc/nginx/{{ item }}"
    state: directory
  with_items:
    - sites-enabled
    - sites-available

- name: Copy nginx config and snippets
  copy:
    src: "{{ item }}"
    dest: "/etc/nginx/{{ item }}"
  with_items:
    - "nginx.conf"
    - "snippets/"
  notify: Restart nginx

- name: Ensure nginx is enabled
  service:
    name: nginx
    state: started
    enabled: yes
