---
- name: Ensure there is a http user
  user:
    name: http
    shell: /usr/bin/nologin
    system: yes

- name: Install nginx on Arch
  pacman:
    name: nginx-mainline
    state: latest
  when: ansible_distribution == "Archlinux"

- name: Install nginx on CentOS
  yum:
    name: "{{ item }}"
    state: latest
  when: ansible_distribution == "CentOS"
  with_items:
    - epel-release
    - nginx

- name: Create vhost directories
  file:
    dest: "/etc/nginx/{{ item }}"
    state: directory
  with_items:
    - sites-enabled
    - sites-available

- name: Copy config
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: "Restart webserver"

- name: Copy snippets
  copy:
    src: "snippets/"
    dest: "/etc/nginx/snippets/"
  notify: "Restart webserver"

- name: Ensure nginx is enabled & running
  service:
    name: nginx
    state: started
    enabled: yes
