---
- name: Create screenshot user
  user:
    name: screenshot
    home: /srv/http/screenshots
    system: yes
    shell: /bin/sh
    comment: Host screenshots at i.rxn.be

- name: Create directory for screenshots
  file:
    path: /srv/http/screenshots
    state: directory
    owner: screenshot
    group: http
    mode: u=rw,g=r,o=

- name: Create ssh direcotory (for authorized_keys)
  file:
    path: /srv/http/screenshots/.ssh
    state: directory
    owner: screenshot
    mode: u=rw,g=,o=

