---
- name: Create screenshot user
  user:
    name: screenshot
    home: /srv/http/screenshots
    system: yes
    shell: /bin/sh
    comment: Host screenshots

- name: Create directory for screenshots
  file:
    path: /srv/http/screenshots
    state: directory
    owner: screenshot
    group: http
    mode: u=rwx,g=rx,o=rx

