---
- name: Install phpMyAdmin
  pacman:
    name: phpmyadmin
    state: present

- name: Copy configuration
  template:
    src: config.inc.php.j2
    dest: /etc/webapps/phpmyadmin/config.inc.php

- name: Check if database exists
  shell:  mysql -e 'SHOW DATABASES;' | grep 'phpmyadmin'
  ignore_errors: yes
  register: pma_dbstatus

- name: Create database
  shell: mysql -u root < /usr/share/webapps/phpMyAdmin/sql/create_tables.sql
  when: pma_dbstatus.rc == 1

- name: Create pma user and grant privileges
  mysql_user:
    name: pma
    host: localhost
    password: '{{ phpmyadmin_db_password }}'
    priv: "mysql.*:USAGE/mysql.user:SELECT(Host,User,Select_priv,Insert_priv,Update_priv,Delete_priv,Create_priv,Drop_priv,Reload_priv,Shutdown_priv,Process_priv,File_priv,Grant_priv,References_priv,Index_priv,Alter_priv,Show_db_priv,Super_priv,Create_tmp_table_priv,Lock_tables_priv,Execute_priv,Repl_slave_priv,Repl_client_priv)/mysql.db:SELECT/mysql.host:SELECT/mysql.tables_priv:SELECT(Host,Db,User,Table_name,Table_priv,Column_priv)/phpmyadmin.*:SELECT,INSERT,UPDATE,DELETE"
