---

- name: Create webroot directory
  file:
    path: "{{ theatervolta_webroot }}"
    state: directory
    owner: http
    group: http

- name: Clone GitHub repo locally
  git:
    repo: git@github.com:R13N/Volta.git
    dest: theatervolta.be
  delegate_to: localhost

- name: Install dependencies
  shell: bundle install
  args:
    chdir: theatervolta.be
  delegate_to: localhost

- name: Compile the site with nanoc
  shell: bundle exec nanoc
  args:
    chdir: theatervolta.be
  delegate_to: localhost

- name: Deploy the site
  shell: bundle exec nanoc deploy
  args:
    chdir: theatervolta.be
  delegate_to: localhost
