---
- name: Install transmission
  yum:
    pkg: '{{ item }}'
    state: latest
    update_cache: yes
  with_items:
    - epel-release
    - python-passlib
    - transmission-daemon
    - transmission-common
    - transmission-cli

- set_fact:
    transmission_service: transmission-daemon
