---
- name: Distribution specific installation
  include: "{{ ansible_distribution }}.yml"


- name: Stop transmission
  service:
    name: "{{ transmission_service }}"
    state: stopped

- name: Create directories
  file:
    state: directory
    owner: transmission
    group: transmission
    recurse: yes
    path: "{{ item }}"
  with_items:
    - /var/lib/transmission/.config/transmission-daemon
    - "{{ transmission_download_dir }}"
    - "{{ transmission_incomplete_dir }}"

- name: Copy configuration file
  template:
    src: settings.json.j2
    dest: /var/lib/transmission/.config/transmission-daemon/settings.json
    owner: transmission
    group: transmission

- name: Create htpasswd file
  htpasswd:
    path: /etc/nginx/transmission_passwd
    name: "{{ transmission_username }}"
    password: "{{ transmission_password }}"

- name: Start and enable transmission
  service:
    name: "{{ transmission_service }}"
    state: started
    enabled: yes
