---
- name: Install postfix and mailx
  yum:
    name: "{{ item }}"
    state: latest
  notify: Reload postfix
  with_items:
    - postfix
    - mailx

- name: Give postfix access to letsencrypt certificates
  user:
    name: postfix
    groups: letsencrypt
    append: yes

- name: Copy postfix config
  template:
    src: "{{ item }}"
    dest: "/etc/{{ item }}"
  with_items:
    - postfix/main.cf
    - postfix/master.cf
  notify: Reload postfix

- name: Set virtual mappings
  template:
    src: postfix/virtual
    dest: /etc/postfix/virtual
  notify: Reload virtual

- name: Ensure postfix is running
  service:
    name: postfix
    state: started
    enabled: yes
