---

- name: Set timezone
  file:
    state: link
    src: "/usr/share/zoneinfo/Europe/Brussels"
    dest: "/etc/localtime"
    force: yes

- name: Select distro
  include: "{{ ansible_distribution }}.yml"

