---
- name: Update system
  pacman: update_cache=yes upgrade=yes

- name: Install essential packages configuration.
  pacman: name={{ item }} state=latest
  with_items:
    - base-devel
    - bc
    - dos2unix
    - git
    - hdparm
    - htop
    - httpie
    - lsof
    - neovim
    - nmap
    - python
    - python
    - python2
    - ranger
    - rbenv
    - rsync
    - ruby
    - scp
    - screenfetch
    - smartmontools
    - speedtest-cli
    - thefuck
    - tmux
    - tree
    - unzip
    - vpnc
    - wget
    - zsh

- name: Symlink neovim to vim
  file: src=/bin/nvim dest=/bin/vim state=link
