---
- name: Select distro for installation
  include: "{{ ansible_distribution }}.yml"

- name: Set new domains to an empty list
  set_fact:
    letsencrypt_new_domains: []

- name: Generate strong Diffie-Hellman group
  command: /usr/sbin/openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048
  args:
    creates: "/etc/ssl/certs/dhparam.pem"

- name: Ensure letsencrypt folder exists
  file:
    name: "/var/lib/letsencrypt/"
    state: directory
    owner: http
    group: http
    recurse: yes

- name: Copy systemd unit and timer files
  copy:
    src: "{{ item }}"
    dest: "/usr/lib/systemd/system/{{ item }}"
  with_items:
    - "certbot.service"
    - "certbot.timer"
  register: letsencrypt_systemd_files

- name: Reload systemd daemon if unit or timer file changed
  command: /usr/sbin/systemctl daemon-reload
  when: letsencrypt_systemd_files.changed

- name: Start and enable systemd timer
  service:
    name: certbot.timer
    state: restarted
    enabled: yes
